language: node_js
node_js:
- '0.10'
before_install:
- npm install -g grunt-cli
script:
- grunt deploy
branches:
  only:
  - source
env:
  global:
    secure: I0XA+vTM9v9aHMCLzIw3aGmhPfvVsThY+MtysKFVbS8Q+kE9Ya1FnHYov5Lsm4htbgpT5n+XwX2KgJ84+eaDugiJ1weTb/SLVYldkP3PywZqNj18Hl2r9voHppICC788fJ33govCHO6Bq6JROhRuDamF+ZhBJbU1bfCWnXidLo8=
